name: Android Build and Release

on:
  push:
    branches:
      - main  # Trigger on push to main
  workflow_dispatch:

permissions:
  contents: write  # Required to create/update releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle (cache disabled to avoid post-job cleanup errors)
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Rename APK to Cager.apk
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Cager.apk

      - name: Get timestamp for unique tag
        id: get_tag
        run: echo "TAG_NAME=build-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
          name: Release ${{ steps.get_tag.outputs.TAG_NAME }}
          body: |
            Automated build from main branch.
            Timestamp: ${{ steps.get_tag.outputs.TAG_NAME }}
          files: app/build/outputs/apk/debug/Cager.apk
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
